version: '3.8'

services:
  ollama-cors-proxy:
    build: .
    ports:
      - "${PROXY_PORT:-11435}:${PROXY_PORT:-11435}"
    environment:
      - OLLAMA_HOST=host.docker.internal
      - OLLAMA_PORT=11434
      - PROXY_PORT=11435
      - OLLAMA_URL=http://host.docker.internal:11434
    network_mode: "bridge"